spring:
  application:
    name: api-gateway

server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 1000

eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
    defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    customer:
      sensitive-headers:
      ignore-local-service: false
      ignored-headers:
      path: /customer/**
      serviceId: customer
      stripPrefix: false
    auth-server:
      sensitive-headers:
      ignore-local-service: false
      ignored-headers:
      path: /oauth/**
      serviceId: auth-server
      stripPrefix: false